---
title: "Diffusion Tensor Imaging and Cognition Analysis in Alzheimer’s Disease"
subtitle: "MSc Bioinformatics and Biostatistics"
author: "Carmen Laura Frias Pérez"
output:
  html_document:
    toc_depth: '5'
    df_print: paged
---

```{r, warning = FALSE, message = FALSE}
# Load of required packages
library(dplyr)
library(tidyr)
library(ggplot2)
library(knitr)
library(car)
library(mice)
library(ggsignif)
library(kableExtra)
```

```{r, warning = FALSE}
# Load and preprocess demographic and neurocognitive data
demographic_data <- read.csv("demographic_neurocognitive_tests.csv", sep = ",", header = TRUE) %>%
  # Transform EMCI and LMCI to MCI and SMC to CN to get data from three groups: CN, MCI, and AD
  mutate(Group = case_when(
      Group == "EMCI" ~ "MCI",
      Group == "LMCI" ~ "MCI",
      Group == "SMC" ~ "CN",
      TRUE ~ Group
  ))

# Load volume and DTI metrics extracted from imaging data
imaging_metrics_volume_data <- read.csv("volume_metrics_results.csv", sep = ",", header = TRUE)

# Merge both datasets and remove subjects with missing DTI metrics
analysis_data <- merge(demographic_data, imaging_metrics_volume_data, by = "ID") %>%
  filter(!(ID %in% c("sub-021"))) %>%
  # Order data according to the Groups
  mutate(Group = factor(Group, levels = c("CN", "MCI", "AD"))) 
# Display of data of the first rows
head(analysis_data)
```

```{r}
# Perform multiple data imputation with random forest method in the variables with NA values
imputed_data <- mice(analysis_data%>%select(FAQ_Score,ADAS_Score), method = "rf")

# Fill NA values with the imputed data
imputed_data_values <- mice::complete(imputed_data)

# Check the absence of NA values
sum(is.na(imputed_data_values))
```

```{r}
# Representation of the data distribution between the basal and imputed database
par(mfrow=c(1,2))

# Representation of FAQ_Score distribution 
plot(density(analysis_data$FAQ_Score,na.rm = T),col="purple",main="FAQ_Score")
lines(density(imputed_data_values <- mice::complete(imputed_data)
$FAQ_Score),col="grey")

# Representation of ADAS_Score distribution
plot(density(as.numeric(analysis_data$ADAS_Score),na.rm = T),col="purple",main="ADAS_Score")
lines(density(as.numeric(imputed_data_values <- mice::complete(imputed_data)
$ADAS_Score)),col="grey")
```

```{r}
# Introduce the imputations in the analysis_data NA values
analysis_data <- analysis_data %>%
  mutate(FAQ_Score = imputed_data_values <- mice::complete(imputed_data)
$FAQ_Score, ADAS_Score = imputed_data_values <- mice::complete(imputed_data)
$ADAS_Score)
```

# Descriptive Statistics

```{r, warning = FALSE}
# Calculation of quantity of patients by group
analysis_data %>%
  count(Group, name = "Number of patients")

# Calculation of gender distribution in the general data (numerical and % values)
analysis_data %>% count(Gender) %>% mutate(Percent = round(n / sum(n) * 100, 1))

# Calculation of gender distribution in each group (numerical and % values)
analysis_data %>%
  # Extract data by group
  group_by(Group, Gender) %>%
  # Calculate the number of males and females in each group
  summarise(n = n(), .groups = "drop") %>%
  # Extract the percentage of males and females in each group
  group_by(Group) %>%
  # Calculate the percentage 
  mutate(Percent = round(n / sum(n) * 100, 1))

# Calculate the mean and SD for all numeric variables of the whole dataset
general_stats <- analysis_data %>%
  # Exclude ID, Gender, and Group columns (non-numerical) 
  summarise(across(-c(ID, Gender, Group), list(Mean = ~mean(.x, na.rm = TRUE), SD = ~sd(.x, na.rm = TRUE)), .names = "{.col}_{.fn}")) %>%
  pivot_longer(
    # Reshape columns into rows for better result organization
    cols = everything(), names_to= "Variable", values_to= "Value"
  ) %>%
  # Re-scale of Vol_, MD_, RD_, and AxD_ variables
  mutate(
    Value = case_when (
      grepl("^(Vol)", Variable) ~ Value / 1000,
      grepl("^(MD|RD|AxD)", Variable) ~ Value * 1000,
      TRUE ~ Value
      ),
    Value = round(Value, 3)) 

# Display the first rows of the data obtained
head(general_stats)

# Calculate means and SDs for numeric variables by group
group_stats <- analysis_data %>%
  # Extract data by group
  group_by(Group) %>%
  # Exclude ID and Gender columns (non-numerical) and calculate these parameters for the rest of them
  summarise(across(-c(ID, Gender), list(Mean = ~mean(.x, na.rm = TRUE), SD = ~sd(.x, na.rm = TRUE)), .names = "{.col}_{.fn}")) %>%
  # Reshape columns into rows for better results organization
  pivot_longer(cols = -Group, names_to = "Variable", values_to = "Value") %>%
  # Re-scale of Vol_, MD_, RD_, and AxD_ variables
  mutate(
    Value = case_when (
      grepl("^(Vol)", Variable) ~ Value / 1000,
      grepl("^(MD|RD|AxD)", Variable) ~ Value * 1000,
      TRUE ~ Value
      ), 
    Value = round(Value, 3)) %>%
  pivot_wider(names_from = Group, values_from = Value)

# Display the first rows of the data obtained
head(group_stats)
```

# Descriptive Representations

```{r, warning = FALSE}
# Prepare data for a pie chart showing patient distribution by group
patients_group <- analysis_data %>%
  # Count the number of patients per group
  count(Group) %>%
  # Represent this number as a percentage (%)
  mutate(proportion = n / sum(n), label = paste0(Group, "(", round(proportion * 100, 1), "%)"))

# Pie chart representation 
ggplot(patients_group, aes(x = "", y = proportion, fill = Group)) +
  geom_col(width = 1) +
  coord_polar(theta = "y") +
  geom_text(aes(label = label), position = position_stack(vjust = 0.5)) +
  labs(title = "Distribution of patients by group") +
  theme_void()

# Representation of Age by group with statistical significance symbols
ggplot(analysis_data, aes(x = Group, y = Age, fill = Group)) +
  geom_boxplot() + 
  labs (title = "Boxplot of Age by group", y = "Age", x = "Group") + 
  theme_minimal() +
  geom_signif(comparisons = list(c("CN", "AD")), annotations = "ns", y_position = 105) +
  geom_signif(comparisons = list(c("CN", "MCI")), annotations = "ns", y_position = 100) +
  geom_signif(comparisons = list(c("AD", "MCI")), annotations = "ns", y_position = 95) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.1)))
  
# Representation of Education by group with statistical significance symbols
ggplot(analysis_data, aes(x = Group, y = Education, fill = Group)) +
  geom_boxplot() + 
  labs (title = "Boxplot of Education by group", y = "Education", x = "Group") + 
  theme_minimal() +
  geom_signif(comparisons = list(c("CN", "AD")), annotations = "ns", y_position = 29) +
  geom_signif(comparisons = list(c("CN", "MCI")), annotations = "ns", y_position = 27) +
  geom_signif(comparisons = list(c("AD", "MCI")), annotations = "ns", y_position = 25) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.1)))

# Representation of MMSE_Score by group with statistical significance symbols
ggplot(analysis_data, aes(x = Group, y = MMSE_Score, fill = Group)) +
  geom_boxplot() + 
  labs (title = "Boxplot of MMSE_Score by group", y = "MMSE_Score", x = "Group") + 
  theme_minimal() +
  geom_signif(comparisons = list(c("CN", "AD")), annotations = "***", y_position = 35) +
  geom_signif(comparisons = list(c("CN", "MCI")), annotations = "***", y_position = 33) +
  geom_signif(comparisons = list(c("AD", "MCI")), annotations = "***", y_position = 31) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.1)))

# Representation of FAQ_Score by group with statistical significance symbols
ggplot(analysis_data, aes(x = Group, y = FAQ_Score, fill = Group)) +
  geom_boxplot() + 
  labs (title = "Boxplot of FAQ_Score by group", y = "FAQ_Score", x = "Group") + 
  theme_minimal() +
  geom_signif(comparisons = list(c("CN", "AD")), annotations = "***", y_position = 33) +
  geom_signif(comparisons = list(c("CN", "MCI")), annotations = "***", y_position = 27) +
  geom_signif(comparisons = list(c("AD", "MCI")), annotations = "***", y_position = 30) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.1)))

# Representation of CDR_Score by group with statistical significance symbols
ggplot(analysis_data, aes(x = Group, y = CDR_Score, fill = Group)) +
  geom_boxplot() + 
  labs (title = "Boxplot of CDR_Score by group", y = "CDR_Score", x = "Group") + 
  theme_minimal() +
  geom_signif(comparisons = list(c("CN", "AD")), annotations = "***", y_position = 1.2) +
  geom_signif(comparisons = list(c("CN", "MCI")), annotations = "***", y_position = 1.02) +
  geom_signif(comparisons = list(c("AD", "MCI")), annotations = "***", y_position = 1.10) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.1)))

# Representation of ADAS_Score by group with statistical significance symbols
ggplot(analysis_data, aes(x = Group, y = ADAS_Score, fill = Group)) +
  geom_boxplot() + 
  labs (title = "Boxplot of ADAS_Score by group", y = "ADAS_Score", x = "Group") + 
  theme_minimal() +
  geom_signif(comparisons = list(c("CN", "AD")), annotations = "***", y_position = 46) +
  geom_signif(comparisons = list(c("CN", "MCI")), annotations = "***", y_position = 38) +
  geom_signif(comparisons = list(c("AD", "MCI")), annotations = "***", y_position = 42) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.1)))

# Representation of Vol_total by group with statistical significance symbols
ggplot(analysis_data, aes(x = Group, y = Vol_total, fill = Group)) +
  geom_boxplot() + 
  labs (title = "Boxplot of Vol_total by group", y = "Vol_total", x = "Group") + 
  theme_minimal() +
  geom_signif(comparisons = list(c("CN", "AD")), annotations = "ns", y_position = 1500000) +
  geom_signif(comparisons = list(c("CN", "MCI")), annotations = "ns", y_position = 1400000) +
  geom_signif(comparisons = list(c("AD", "MCI")), annotations = "*", y_position = 1450000) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.1)))

# Representation of FA_global by group with statistical significance symbols
ggplot(analysis_data, aes(x = Group, y = FA_global, fill = Group)) +
  geom_boxplot() + 
  labs (title = "Boxplot of FA_global by group", y = "FA_global", x = "Group") + 
  theme_minimal() +
  geom_signif(comparisons = list(c("CN", "AD")), annotations = "ns", y_position = 0.32) +
  geom_signif(comparisons = list(c("CN", "MCI")), annotations = "*", y_position = 0.30) +
  geom_signif(comparisons = list(c("AD", "MCI")), annotations = "*", y_position = 0.31) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.1)))

# Representation of MD_global by group with statistical significance symbols
ggplot(analysis_data, aes(x = Group, y = MD_global, fill = Group)) +
  geom_boxplot() + 
  labs (title = "Boxplot of MD_global by group", y = "MD_global", x = "Group") + 
  theme_minimal() +
  geom_signif(comparisons = list(c("CN", "AD")), annotations = "ns", y_position = 0.00175) +
  geom_signif(comparisons = list(c("CN", "MCI")), annotations = "***", y_position = 0.0016) +
  geom_signif(comparisons = list(c("AD", "MCI")), annotations = "**", y_position = 0.001675) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.1)))

# Representation of RD_global by group with statistical significance symbols
ggplot(analysis_data, aes(x = Group, y = RD_global, fill = Group)) +
  geom_boxplot() + 
  labs (title = "Boxplot of RD_global by group", y = "RD_global", x = "Group") + 
  theme_minimal() +
  geom_signif(comparisons = list(c("CN", "AD")), annotations = "ns", y_position = 0.001575) +
  geom_signif(comparisons = list(c("CN", "MCI")), annotations = "***", y_position = 0.001425) +
  geom_signif(comparisons = list(c("AD", "MCI")), annotations = "***", y_position = 0.0015) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.1)))

# AxD_global
ggplot(analysis_data, aes(x = Group, y = AxD_global, fill = Group)) +
  geom_boxplot() + 
  labs (title = "Boxplot of AxD_global by group", y = "AxD_global", x = "Group") + 
  theme_minimal() +
  geom_signif(comparisons = list(c("CN", "AD")), annotations = "*", y_position = 0.00215) +
  geom_signif(comparisons = list(c("CN", "MCI")), annotations = "***", y_position = 0.00195) +
  geom_signif(comparisons = list(c("AD", "MCI")), annotations = "**", y_position = 0.00205) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.1)))
```

# General and Post-hoc Analysis of the Data

```{r, warning = FALSE}
# Analysis for Gender variable distribution
gender_table <- table(analysis_data$Group, analysis_data$Gender)
chisq.test(gender_table)

# Extract names of all numeric variables
numeric_values_analyse <- analysis_data %>% select(where(is.numeric)) %>% names()

# Hypothesis tests and post-hoc analysis

# Create a list to store general analysis results 
analysis_results <- list()

# Create a list to score post-hoc analysis
posthoc_analysis <- list()

# Run normality and homogeneity assumptions, as well as general analysis and post-hoc analysis
for(var in numeric_values_analyse) {
  
  # Repeat the formula in each numerical variable of each group
  formula <- reformulate("Group", response = var)
  
  # Perform ANOVA model
  model_ANOVA <- aov(formula, data = analysis_data)
  
  # Get the residuals of this model
  model_residuals <- residuals(model_ANOVA)
  
  # Perform Shapiro-Wilk test for normality 
  shapiro_test <- tryCatch(shapiro.test(model_residuals)$p.value, error = function(e) NA)
  
  # Determine that the results are normal if p-value > 0.05
  normal <- !is.na(shapiro_test) && shapiro_test > 0.05
  
  # Perform Levene's test for homogeneity of variance
  levene_test <- tryCatch(leveneTest(formula, data = analysis_data)$'Pr(>F)'[1], error = function(e) NA)
  
  # Determine that the results are homogenous if p-value > 0.05
  homogeneous <- !is.na(levene_test) && levene_test > 0.05
  
  # Consider the previous assumptions to decide the test to be used
  # If the variables are normal and homogeneous
  if(normal && homogeneous) {
    # Perform ANOVA and extract its p-value
    test <- "ANOVA"
    pval <- summary(model_ANOVA)[[1]][["Pr(>F)"]][1]
  # If the variables are not normal and/or homogeneous
  } else {
    # Perform Kruskal-Wallis and extract its p-value
    test <- "Kruskal-Wallis"
    pval <- kruskal.test(formula, data = analysis_data)$p.value
  }
  
  # Write the results on the list previously created
  analysis_results[[var]] <- tibble(
    # Name of the variables
    Variable = var,
    # Normality condition of the variables
    Normality = ifelse(is.na(shapiro_test), "Error", ifelse(normal, "Yes", "No")),
    # Homogeneity condition of the variables
    Homogeneity = ifelse(is.na(levene_test), "Error", ifelse(homogeneous, "Yes", "No")),
    # Test used according to the aforementioned assumptions
    Test = test,
    # Extract p-value with scientific notation and 2 decimals
    p_value = formatC(pval, format = "e", digits = 2),
  )
  
  # Execute post-hoc analysis in all significant results obtained
  if (pval < 0.05) {
    # If ANOVA was used to the statistical analysis, perform TukeyHSD post-hoc analysis
    posthoc_analysis[[var]] <- if (test == "ANOVA") TukeyHSD(model_ANOVA)
    # If Kruskal-Wallis was used to the statistical analysis, perform Wilcoxon signed rank test with pairwise comparisons
    else pairwise.wilcox.test(analysis_data[[var]], analysis_data$Group, p.adjust.method = "bonferroni")
  }
}

# Merge normality and homogeneity assumptions and general analysis results in a table
general_results <- bind_rows(analysis_results)

# Display of the table with normality and homogeneity assumptions and general analysis results
kable(general_results)

# Modify format of post-hoc results

# Create another list to score posthoc_results
posthoc_results <- list()

# Run format modification of posthoc_results into a table
for(var in names(posthoc_analysis)) {
  
  posthoc_variable <- posthoc_analysis[[var]]
  
  # If TukeyHSD analysis was used
  if (inherits(posthoc_variable, "TukeyHSD")) {
    # Extract the results
    df_posthoc <- as.data.frame(posthoc_variable$Group)
    # Define the colnames to be considered 
    df_posthoc$Comparison <- rownames(df_posthoc)
    df_posthoc$Variable <- var
    df_posthoc$Test <- "Tukey"
    # Create the columns     
    df_posthoc <- df_posthoc[, c("Variable", "Comparison", "p adj", "Test")]
    # Rename p-value column
    names(df_posthoc)[3] <- "p_value"
    # Write TukeyHSD results in the created dataframe
    posthoc_results[[var]] <- df_posthoc
    # If Wilcoxon analysis was used
  } else if (inherits(posthoc_variable, "pairwise.htest")) {
    # Extract its p-value
    df_posthoc <- posthoc_variable$p.value
    # Skip if there are invalid values for the dataframe
    if (is.null(df_posthoc) || length(df_posthoc) == 0 || nrow(df_posthoc) == 0 || ncol(df_posthoc) == 0) {
      next
    }

    # Ensure names of rows and columns
    if (is.null(rownames(df_posthoc))) rownames(df_posthoc) <- seq_len(nrow(df_posthoc))
    if (is.null(colnames(df_posthoc))) colnames(df_posthoc) <- seq_len(ncol(df_posthoc))
    
    # Reshape the previous matrix into a long format adding the groups that are being compared and the test used
    df_long_posthoc <- reshape2::melt(as.matrix(df_posthoc), varnames = c("Group1", "Group2"), value.name = "p_value") %>%
      filter(!is.na(p_value)) %>%
      mutate(
        Variable = var,
        Comparison = paste(Group1, "-", Group2),
        Test = "Wilcoxon"
      ) %>%
      select(Variable, Comparison, Test, p_value)
    # Write the results in the posthoc_results list prepared
    posthoc_results[[var]] <- df_long_posthoc
  }
}

# Merge post-hoc results in the same table
posthoc_table <- bind_rows(posthoc_results) %>%
  mutate(
    # Extract p-value with scientific notation and 2 decimals
    p_value = formatC(as.numeric(p_value), format = "e", digits = 2),
  )

# Visualize the post-hoc results
kable(posthoc_table, row.names = FALSE)
```

# Correlation study between neurocognitive scores and significant image variables

```{r, warning = FALSE}
# Define neurocognitive variables: MMSE_Score, FAQ_Score, CDR_Score, ADAS_Score
neurocognitive_var <- analysis_data[,6:10]

# Define volume and DTI metrics achieved from image analysis: Vol_total, FA_global, MD_global, RD_global, AxD_global and by brain region
image_var <- names(analysis_data)[11:ncol(analysis_data)]

# Add a filter to do the correlation study with the significant imaging variables
image_var_sig <- general_results %>%
  filter(as.numeric(p_value) < 0.05 , Variable %in% image_var) %>%
  pull(Variable)

# Create a dataset to only include the significant imaging variables
image_analysis_results <- analysis_data[, image_var_sig]

# Generate a correlation table with the correlation coefficient (r) and p-value to study the relationship between these variables
correlation_results <- expand.grid(Neurocognitive_Tests = names(neurocognitive_var), Image_Analysis_Results = image_var_sig, stringsAsFactors = FALSE) %>%
  rowwise() %>%
  mutate(
    Correlation = cor(analysis_data[[Neurocognitive_Tests]], analysis_data[[Image_Analysis_Results]], use = "complete.obs"),
    p_value = cor.test(analysis_data[[Neurocognitive_Tests]], analysis_data[[Image_Analysis_Results]])$p.value
  ) %>%
  ungroup() %>%
  mutate(
    p_value = formatC(as.numeric(p_value), format = "e", digits = 2),
  )

# Display of the correlation results
kable(correlation_results)
```
